# Generated by Django 4.2.5 on 2023-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_category_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Dress', 'Dress'), ('Extras', 'Extras'), ('Accessories', 'Accessories'), ('Footwear', 'Footwear')], default='top', max_length=100),
        ),
    ]
